name: Wait for HTTP Status
description: Pings the provided URL until it responds with a healthy status code.
inputs:
  url:
    description: "The fully-qualified URL to ping"
    required: true
  status:
    description: "The status code that implies the URL is healthy. Defaults to 200"
    required: false
    default: "200"
  timeout_seconds:
    description: "The number of seconds the action will try pinging the URL until it is considered a failure. Defaults to 900 (15 min)"
    required: false
    default: "900"
  interval_seconds:
    description: "The number of seconds in between each ping attempt. Defaults to 15"
    required: false
    default: "15"
runs:
  using: composite
  steps:
    - name: Ping URL
      shell: bash
      run: node "${GITHUB_WORKSPACE}/.github/actions/wait-for-http-status/scripts/ping-url.js" ${{ inputs.url }} ${{ inputs.status }} ${{ inputs.timeout_seconds }} ${{ inputs.interval_seconds }}
