name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  # determining CI workflow status (aggregate of all jobs) - read
  # delete docker oci tarball workflow artifact
  actions: write
  contents: read # checking out the source code
  pull-requests: write # adding labels to PRs

jobs:
  test-kong-gateway:
    name: Test Kong Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Test Kong Gateway
        uses: ./.github/actions/test-kong-gateway/
        with:
          gateway-config-path: gateway_config.yml
          assertions-path: assertions.json
