name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  actions: write
  contents: read # checking out the source code
  pull-requests: write # adding labels to PRs

jobs:
  dump-env:
    runs-on:
#      group: 'Default' groups are only available for Enterprise accounts, organizations owned by enterprise accounts, and organizations using GitHub Teams
      labels: ${{ (contains( github.event.pull_request.labels.*.name, 'selfishly-hosted-runner') && format('{0}-laptop', github.actor)) || 'ubuntu-latest' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"
